# Generated by Django 5.2.12 on 2026-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_cardimage_histogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimage',
            name='histogram',
            field=models.CharField(max_length=512),
        ),
    ]
